export const GET_LOCAL_USER = 'GET_LOCAL_USER'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'

export const TAB_INIT = 'TAB_INIT'
export const TAB_CREATE = 'TAB_CREATE'
export const TAB_SWITCH = 'TAB_SWITCH'
export const TAB_CLOSE = 'TAB_CLOSE'
export const TAB_CLEAR = 'TAB_CLEAR'

export const OPEN_PERSONNEL_DIALOG = 'OPEN_PERSONNEL_DIALOG'
export const CLOSE_PERSONNEL_DIALOG = 'CLOSE_PERSONNEL_DIALOG'
export const OPEN_PERSONNEL_MULTIPLE_DIALOG = 'OPEN_PERSONNEL_MULTIPLE_DIALOG'

export const OPEN_FILE_DIALOG = 'OPEN_FILE_DIALOG'
export const CLOSE_FILE_DIALOG = 'CLOSE_FILE_DIALOG'
export const OPEN_FILE_MULTIPLE_DIALOG = 'OPEN_FILE_MULTIPLE_DIALOG'

export const CREATE_UPLOAD = 'CREATE_UPLOAD'
export const OPEN_FILE_SELECT = 'OPEN_FILE_SELECT'
export const CHANGE_FILE_PROGRESS = 'CHANGE_FILE_PROGRESS'
